### ISSUE TITLE
Bug in the implementation of the range check 

### ISSUE THREAD

**Issue by Vishalkulkarni45** [qope/starky-fq12#7]
@qope 
Range check circuit is under-constrained because there is no constrain between the column being checked and the permuted input. Replace the generate_trace function with the below code https://github.com/qope/starky-bn254/blob/main/src/utils/lookup.rs#L152
```
 let inputs = vec![6, 3, 1, 1, 0, 0, 0, 0]
                .iter()
                .map(|&x| F::from_canonical_u32(x))
                .collect_vec();
 let table = vec![0, 1, 2, 3, 4, 5, 6, 7]
                .iter()
                .map(|&x| F::from_canonical_u32(x))
                .collect_vec();
let (permuted_input, permuted_table) = permuted_cols(&inputs, &table);

 let incorrect_inputs = [10, 30, 15, 100, 2, 50, 43, 61]
                .iter()
                .map(|&x| F::from_canonical_u32(x))
                .collect_vec();
                
 let cols = vec![incorrect_inputs, table, permuted_input, permuted_table];

```
I replaced the actual inputs with the incorrect-inputs which are out of range and still able to verify the stark

**Comment by qope** [comment]
Thank you for the issue. The link is not working for me.

**Comment by Vishalkulkarni45** [comment]
@qope Sorry , Is it now clear ?

**Comment by qope** [comment]
The relationship between `inputs` and `permuted_input`, as well as `table` and `permuted_table`, being in a permutation, needs to be constrained using `permutation_pairs` trait. I have modified the test code in `lookup.rs`, so please check it.
Other than the test code in `lookup.rs`, everything else should be fine as they are already constrained by `permutation_pairs`.

**Comment by Vishalkulkarni45** [comment]
Thank you

**Comment by Vishalkulkarni45** [comment]
Thanks
